### ISSUE TITLE
Cannot use npm package.

### ISSUE THREAD

**Issue by ricardo-afonso** [dutiyesh/chrome-extension-cli#11]
Used the CLI to generate a new project and installed an npm package that has dependencies. On running the extension, the npm package is loaded but its dependencies throw a 'not found' error.

**Comment by dutiyesh** [comment]
@ricardo-afonso Can you share the complete error message?
And what was the package name and version that you installed?

**Comment by ricardo-afonso** [comment]
Already tried with a few different packages, but all of the same kind, and the error seems to be consistent. The one I mainly wanted to use is 'yt-search'.  Upon importing or requiring the package, either in contentScript.js or popup.js, I get an error message on the dev console stating that it can't find it's first used dependency, in this case, `Uncaught Error: Cannot find module 'cheerio'
    at o (contentScript.js:291)`

**Comment by dutiyesh** [comment]
The error is coming because `yt-search` and its dependency package `cheerio` works in node.js application and not on browser.
For extension you will have to install packages that work on browser.
