### ISSUE TITLE
update to latest version of webpack for project creation

### ISSUE THREAD

**Issue by krthush** [dutiyesh/chrome-extension-cli#25]
I noticed that optional chaining wasn't working (e.g. var.var?.var)

Realised that an outdated version of webpack was being used 

![image](https://user-images.githubusercontent.com/33790334/167625740-918e08be-7128-45c5-a4b1-2b81594b4b35.png)

Is there any chance we can update the cli to generate projects with the most recent version of webpack?

**Comment by dutiyesh** [comment]
Hi @krthush, with help of @Bilal-io's contribution we have upgraded webpack and other dependencies in CLI's [1.2.0](https://github.com/dutiyesh/chrome-extension-cli/releases/tag/v1.2.0) version.
