### ISSUE TITLE
npm ERR! Missing script: "watch"

### ISSUE THREAD

**Issue by GildedHonour** [dutiyesh/chrome-extension-cli#30]
Hello world, from the README:

```
//...........

% cd my-extension
% npm run watch
npm ERR! Missing script: "watch"
```

**Comment by dutiyesh** [comment]
Hi @GildedHonour, can you check if there is a `"watch"` script present inside `"scripts"` object of `package.json` file?
If it is not present then kindly re-create the extension using cli command - `chrome-extension-cli <project-name>`.
