### ISSUE TITLE
Will sidePanel being supported?

### ISSUE THREAD

**Issue by cyfung1031** [dutiyesh/chrome-extension-cli#39]
Since Chrome Beta 114, sidePanel is added as extension API.

Will it be supported in this CLI?

https://developer.chrome.com/docs/extensions/reference/sidePanel/

**Comment by dutiyesh** [comment]
Yes, a support will be added for it.

**Comment by dutiyesh** [comment]
Side Panel support has been added in [v1.5.0](https://github.com/dutiyesh/chrome-extension-cli/releases/tag/v1.5.0)
