### ISSUE TITLE
Could not load manifest.

### ISSUE THREAD

**Issue by ftp5500** [dutiyesh/chrome-extension-cli#8]
When trying to load the extension I get this error!

Could not load javascript 'contentScript.js' for content script.
Could not load manifest.

**Comment by dutiyesh** [comment]
Did you select `build/` folder while loading the extension in Chrome browser?
See if you have followed [these steps](https://github.com/dutiyesh/chrome-extension-cli#npm-run-watch).

**Comment by ftp5500** [comment]
> Did you select `build/` folder while loading the extension in Chrome browser?
> See if you have followed [these steps](https://github.com/dutiyesh/chrome-extension-cli#npm-run-watch).

Yes I did

**Comment by ftp5500** [comment]
> Did you select `build/` folder while loading the extension in Chrome browser?
> See if you have followed [these steps](https://github.com/dutiyesh/chrome-extension-cli#npm-run-watch).


Yes I did

**Comment by dutiyesh** [comment]
Could your share your `build/manifest.json` file code here?
